name: ENV variables
on: push
env:
    WF_ENV: Available to all jobs
jobs:
    log-env:
        runs-on: ubuntu-latest
        env:
            JOB_ENV: Available to all  steps in this job
        steps:
          - name: Log envirnment variables
            env:
              STEP_ENV: Available only to this step
            run: |
              echo "WF_ENV: ${WF_ENV}"
              echo "JOB_ENV: ${JOB_ENV}"
              echo "STEP_ENV: ${STEP_ENV}"
          - name: log env2
            run: |
              echo "WF_ENV: ${WF_ENV}"
              echo "JOB_ENV: ${JOB_ENV}"
              echo "STEP_ENV: ${STEP_ENV}"
    log-default-env:
        runs-on: ubuntu-latest
        steps:
          - name: Log default environment variables
            run: |
              echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
              echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
              echo "GITHUB_JOB: ${GITHUB_JOB}"
              echo "WF_ENV: ${WF_ENV}"
              echo "JOB_ENV: ${JOB_ENV}"
              echo "STEP_ENV: ${STEP_ENV}"